# Generated by Django 6.0.3 on 2026-04-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecamp', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='treking/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.country')),
            ],
        ),
    ]
