# Generated by Django 6.0.3 on 2026-04-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20260416_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='test',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('treking', 'Treking'), ('camping', 'Camping'), ('caravan', 'Caravan')], max_length=20),
        ),
    ]
