# Generated by Django 6.0.3 on 2026-04-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_camping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camping',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='camping/'),
        ),
        migrations.CreateModel(
            name='Caravan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField()),
                ('amenties', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='caravan/')),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.country')),
            ],
        ),
    ]
