# Generated by Django 6.0.3 on 2026-04-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_booking_test_alter_booking_booking_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
    ]
