# Generated by Django 6.0.3 on 2026-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='checkin',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='checkout',
            new_name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='item_type',
            field=models.CharField(choices=[('trek', 'Treking'), ('camp', 'Camping'), ('caravan', 'Caravan')], max_length=10),
        ),
    ]
