# Generated by Django 6.0.3 on 2026-05-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
